website/music/urls.py
from . import views
from django.urls import path

app_name='music'

urlpatterns = [

    path('<int:album_id>/', views.detail, name='detail'),
    path('', views.index, name= 'index'),
    path('<int:album_id>/favorite/', views.favorite, name='favorite'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
]

website/music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre= models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)



    def __str__(self):
        return self.album_title +' -'+ self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250, default="ghufgj")
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

website/music/views.py
from .models import Album
from django.shortcuts import render, get_object_or_404

def index(request):
    all_albums = Album.objects.all()

    context = {'all_albums': all_albums}

    return render(request, 'music/index.html', context)

def detail(request, album_id ):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album' : album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk = request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_message':"You selected the wrong option",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album':album})
'''
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']
'''

website/music/templates/music/detail.html
<img src = "{{ album.album_logo }}">

<h1> {{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}


        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://vignette.wikia.nocookie.net/logopedia/images/5/5b/Hot_Star_Logo.png/revision/latest?cb=20170304041050" height="42" width="42" />


            {% endif %}
        </label><br>

    {% endfor %}
    <input type="submit" value="favorite">



</form>

website/music/templates/music/index.html
{% if all_albums %}
    <h3>Here all my albums</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}

    </ul>
{% else %}
    <h3> You dont have any albums</h3>

{% endif %}